# 로컬 환경에서 사용하는 정보들은 여기에 설정한다.
spring:
  h2:
    console:
      enabled: true
      path: /h2     # Context path
  datasource:
    url: jdbc:h2:mem:test     # JDBC URL
  jpa:
    hibernate:
      ddl-auto: create    # 스키마 자동 생성
    show-sql: true        # SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # SQL pretty print
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
logging:                  # JPA 로그 레벨 설정
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true