spring:
  h2:
    console:
      enabled: true
      path: /h2     # Context path
  datasource:
    url: jdbc:h2:mem:test     # JDBC URL
  jpa:
    hibernate:
      ddl-auto: create    # 스키마 자동 생성
    show-sql: true        # SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # SQL pretty print
logging:                  # JPA 로그 레벨 설정
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG